name: secrets.yml
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - run: echo "La clef est égale à $API_KEY"
