name: secrets.yml
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: debug
        if: ${{ secrets.API_KEY }}
        run: echo "La clef n'est pas vide"
      - run: echo "La clef est ${{ secrets.API_KEY }}"
