name: with-action.yml
on: workflow_dispatch
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  inspect-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0

      - name: lister les fichiers
        run: ls -l

      - name: Afficher README
        run: cat README.md
